# 230206 sklearn 내장 데이터셋 연습 - iris data

In [10]:
import numpy as np
#sklearn의 toy dataset import 
from sklearn.datasets import load_iris
import sklearn
from sklearn import datasets

In [3]:
sklearn.__version__

'1.2.1'

In [5]:
dir(datasets)

['__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arff_parser',
 '_base',
 '_california_housing',
 '_covtype',
 '_kddcup99',
 '_lfw',
 '_olivetti_faces',
 '_openml',
 '_rcv1',
 '_samples_generator',
 '_species_distributions',
 '_svmlight_format_fast',
 '_svmlight_format_io',
 '_twenty_newsgroups',
 'clear_data_home',
 'dump_svmlight_file',
 'fetch_20newsgroups',
 'fetch_20newsgroups_vectorized',
 'fetch_california_housing',
 'fetch_covtype',
 'fetch_kddcup99',
 'fetch_lfw_pairs',
 'fetch_lfw_people',
 'fetch_olivetti_faces',
 'fetch_openml',
 'fetch_rcv1',
 'fetch_species_distributions',
 'get_data_home',
 'load_breast_cancer',
 'load_diabetes',
 'load_digits',
 'load_files',
 'load_iris',
 'load_linnerud',
 'load_sample_image',
 'load_sample_images',
 'load_svmlight_file',
 'load_svmlight_files',
 'load_wine',
 'make_biclusters',
 'make_blobs',
 'make_checkerboard',
 'make_circl

In [6]:
#데이터 수집부터 
#일단 메모리에 넣음
iris = load_iris()


In [7]:
#bunch라는 자료구조 안에 들어있음 
type(iris)

sklearn.utils._bunch.Bunch

In [9]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [10]:
iris.keys()
#key가 있으니 value도 있겠구나!

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [18]:
#iris의 describe
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [19]:
#특성 데이터 확인 
print(iris.data)
#dir 로 키 값 뭐 있는지 찍어본거임 
print(iris.feature_names)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [16]:
#2차원 Array임 -> , 도 없고 뭐 암튼 ㅇㅇ
#150개의 꽃 정보를 갖고 있을 것임 
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [17]:
#타겟 데이터 확인 
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [20]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


In [21]:
len(iris.data)

150

In [22]:
print(iris.filename)

iris.csv


In [23]:
#데이터 입루 확인하기 
# 파이썬 식으로 인덱싱 하려면 슬라이싱
# 앞에서부터 5개 HEAD는 데이터 프레임에서 쓰는 거임
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [24]:
#EDA로 볼 때는 numpy보기 힘들어! 그래서 데이터 탐색할 때엔 pandas df 으로 해서 봄
import pandas as pd

In [26]:
df_X = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df_X

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [28]:
#학습용 데이터와 검증용 데이터를 따로 구분해놓아야 함 
from sklearn.model_selection import train_test_split

#psedo seed number 랜덤 시드 넘버를 결정

In [29]:
# 변수명도 관습적으로 학습, 검증을 아래처럼 구분함 
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, \
                                                    random_state=42)


In [31]:
train_test_split(iris.data, iris.target, test_size=0.3, \
                                                    random_state=42)
#꽃의 데이터를 7대 3으로 나눔

[array([[5.5, 2.4, 3.7, 1. ],
        [6.3, 2.8, 5.1, 1.5],
        [6.4, 3.1, 5.5, 1.8],
        [6.6, 3. , 4.4, 1.4],
        [7.2, 3.6, 6.1, 2.5],
        [5.7, 2.9, 4.2, 1.3],
        [7.6, 3. , 6.6, 2.1],
        [5.6, 3. , 4.5, 1.5],
        [5.1, 3.5, 1.4, 0.2],
        [7.7, 2.8, 6.7, 2. ],
        [5.8, 2.7, 4.1, 1. ],
        [5.2, 3.4, 1.4, 0.2],
        [5. , 3.5, 1.3, 0.3],
        [5.1, 3.8, 1.9, 0.4],
        [5. , 2. , 3.5, 1. ],
        [6.3, 2.7, 4.9, 1.8],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [5.6, 2.7, 4.2, 1.3],
        [5.1, 3.4, 1.5, 0.2],
        [5.7, 3. , 4.2, 1.2],
        [7.7, 3.8, 6.7, 2.2],
        [4.6, 3.2, 1.4, 0.2],
        [6.2, 2.9, 4.3, 1.3],
        [5.7, 2.5, 5. , 2. ],
        [5.5, 4.2, 1.4, 0.2],
        [6. , 3. , 4.8, 1.8],
        [5.8, 2.7, 5.1, 1.9],
        [6. , 2.2, 4. , 1. ],
        [5.4, 3. , 4.5, 1.5],
        [6.2, 3.4, 5.4, 2.3],
        [5.5, 2.3, 4. , 1.3],
        [5

In [32]:
#특성과 종속의 벡터쌍으로 데이터로 이루어짐 
# train test split에 줘야하는 데이터는 x, y, testsize 

len(X_train)

105

In [33]:
len(X_test)

45

In [35]:
#데이터 분할을 했고 결정 트리 모델 함 해보자
from sklearn.tree import DecisionTreeClassifier
# 1) 분석을 수행하기 위한 추정치(estimator)생성
cls = DecisionTreeClassifier()

# 2) 해당 객체에 대해 fit()메소드를 수행: 학습수행
cls.fit(X_train, y_train)

# 3) 검증하고 예측 결과 수행 
y_pred = cls.predict(X_test)
# 얘가 값을 내놓을텐데 일단 예를 받아놓아라
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [37]:
# 예측한 것 가지고 몇 개가 맞았나를 보면 됨 
# 모델 평가 
# 생성된 객처 또는 수행된 분석 결과에 대해 적합한 성능 평가 지표 도출
# 검증할 때는 accuracy_score 씀
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)
# 1.0 == 100점, 즉 잘 만들어진 모델이다

1.0

In [ ]:
#일반화 오차 



In [1]:
import pandas as pd


In [136]:
titanic_df = pd.read_csv('data/titanic_train.csv')
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [7]:
# titanic_df['Survived'] #특정 열 하나만 고르는 것 
titanic_df['Survived'].value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [8]:
#1등, 2등, 3등칸 승선한 승객들
titanic_df.Pclass.value_counts()

3    491
1    216
2    184
Name: Pclass, dtype: int64

## DataFrame 과 리스트, 딕셔너리, 넘파이 ndarray 상호 변환
- 넘파이 ndarray, 리스트, 딕셔너리를 DF로 변환하기
 
머신러닝에선 2차원 자료구조, ndarray선언

In [21]:
list1 = [1,2,3]
array1 = np.array(list1) 
# array1을 데이터 프레임으로 변경해보자
col_name = ['col1']
df_list1 = pd.DataFrame(data = list1, columns=col_name)
df_list1

col1
0     1
1     2
2     3

In [24]:
#2차원 데이터 프레임을 만들어보자
list2 = [[1,2,3],
         [11,22,33]]
array2 = np.array(list2)
col_name2 = ['col1', 'col2', 'col3']
df_list2 = pd.DataFrame(list2, columns=col_name2)
df_list2

# dictionary를 데이터 프레임으로 만들어보자 
dic1 = {'col1':[1,11],
        'col2':[2,22],
        'col3':[3,33]}
df_dict1 = pd.DataFrame(dic1)
df_dict1


col1  col2  col3
0     1     2     3
1    11    22    33

In [26]:
# 데이터 프레임을 numpy로 만들어보자
# 머신 러닝에 넣으려면 ndarray로 만들어야 함 
df_dict1.values

array([[ 1,  2,  3],
       [11, 22, 33]])

In [28]:
#리스트로 변환
df_dict1.values.tolist()

[[1, 2, 3], [11, 22, 33]]

In [33]:
df_dict1.to_dict()

{'col1': {0: 1, 1: 11}, 'col2': {0: 2, 1: 22}, 'col3': {0: 3, 1: 33}}

In [34]:
#데이터 프레임 삭제 
# 3) titanic_df 에 "Family_No"열 생성하고 
# 모든 값에 titanic_df["SibSp"]열 데이터와 titianic 'parch 열 데이터 합하고 추가로 1 더해서 할당

In [50]:
# 1) titanic_df에 "Age_0" 열을 생성하고 모든 값을 0으로 설정하라
titanic_df['Age_0'] = 0


In [44]:
# 2) titanic_df에 "Age_by_10" 열을 생성하고 모든 값에 titanic_df["Age"] 열 데이터에 10을 곱하여 각각 할당하라
titanic_df['Age_by_10'] = titanic_df["Age"]*10
# 브로드 캐스팅 




In [54]:
# 3) titanic_df에 "Family_No" 열을 생성하고 
titanic_df["Family_No"] = titanic_df["SibSp"] + titanic_df['Parch'] +1
# 모든 값에 titanic_df["SibSp"] 열 데이터와 titanic_df["ParCh'] 열 데이터를 합하고 추가로 1을 더해서 할당하라
titanic_df.info() #이걸로 데이터 확인해라 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
 12  Age_0        891 non-null    int64  
 13  Age_by_10    714 non-null    float64
 14  Family_No    891 non-null    int64  
dtypes: float64(3), int64(7), object(5)
memory usage: 104.5+ KB


In [55]:
# 4) titanic_df에 "Age_by_10" 열의 모든 데이터에 titanic_df의 "Age_by_10"열 값에 10을 더하여 할당하라
titanic_df["Age_by_10"] = titanic_df["Age_by_10"]+10

In [59]:
# 5) titanic_df의 "Age_0"열을 삭제하라
titanic_df = titanic_df.drop('Age_0', axis=1) #열을 삭제할 때엔 axis 1을 쓴다 행을 삭제할 때엔 axis= 0
# or inplace 를 통해 계속 반영할 것인지를 설정할 수 있다 (defalut ==  False)
# titanic_df.drop('Age_0', axis=1, inplace = True)

In [61]:
# 6) titanic_df의 'Age_0', 'Age_by_10', 'Family_No'열을 삭제하라
titanic_df.drop(['Age_by_10', 'Family_No'], axis = 1, inplace = True)

In [63]:
# 7) titanic_df의 인덱스를 재설정하되, 기존의 인덱스는 컬럼으로 추가하라


In [67]:
#index 의 값을 확인하자
titanic_df.index.values

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [68]:
#index를 새롭게 하고 싶어 이 때 기존의 인덱스를 데이터에 포함시키려면 drop = False 
titanic_df.reset_index(drop=False)
# 리셋 인덱스 하고 이거를 그대로 가져가는 거 되게 중요함

index  PassengerId  Survived  Pclass  \
0        0            1         0       3   
1        1            2         1       1   
2        2            3         1       3   
3        3            4         1       1   
4        4            5         0       3   
..     ...          ...       ...     ...   
886    886          887         0       2   
887    887          888         1       1   
888    888          889         0       3   
889    889          890         1       1   
890    890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 13 columns]

In [70]:
# 8) titanic_df의 열을 참조하는 법
titanic_df["Pclass"]
titanic_df.Pclass #property 참조법

0      3
1      1
2      3
3      1
4      3
      ..
886    2
887    1
888    3
889    1
890    3
Name: Pclass, Length: 891, dtype: int64

In [76]:
#titanic df 에서 3등석 승객 데이터만 조회하라
titanic_df["Pclass"] == 3
#boolean indexing: 원래 데이터에 전부 적용 
titanic_df[titanic_df["Pclass"] == 3]


PassengerId  Survived  Pclass                                      Name  \
0              1         0       3                   Braund, Mr. Owen Harris   
2              3         1       3                    Heikkinen, Miss. Laina   
4              5         0       3                  Allen, Mr. William Henry   
5              6         0       3                          Moran, Mr. James   
7              8         0       3            Palsson, Master. Gosta Leonard   
..           ...       ...     ...                                       ...   
882          883         0       3              Dahlberg, Miss. Gerda Ulrika   
884          885         0       3                    Sutehall, Mr. Henry Jr   
885          886         0       3      Rice, Mrs. William (Margaret Norton)   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0      male  22.0      1      0         A/5 21171   7.2500   NaN        S  
2    female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S  
4      male  35.0      0      0            373450   8.0500   NaN        S  
5      male   NaN      0      0            330877   8.4583   NaN        Q  
7      male   2.0      3      1            349909  21.0750   NaN        S  
..      ...   ...    ...    ...               ...      ...   ...      ...  
882  female  22.0      0      0              7552  10.5167   NaN        S  
884    male  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
885  female  39.0      0      5            382652  29.1250   NaN        Q  
888  female   NaN      1      2        W./C. 6607  23.4500   NaN        S  
890    male  32.0      0      0            370376   7.7500   NaN        Q  

[491 rows x 12 columns]

In [78]:
# 60세 이상인 승객 정보를 구하여라 
titanic_df[titanic_df["Age"]>=60]

PassengerId  Survived  Pclass  \
33            34         0       2   
54            55         0       1   
96            97         0       1   
116          117         0       3   
170          171         0       1   
252          253         0       1   
275          276         1       1   
280          281         0       3   
326          327         0       3   
366          367         1       1   
438          439         0       1   
456          457         0       1   
483          484         1       3   
493          494         0       1   
545          546         0       1   
555          556         0       1   
570          571         1       2   
587          588         1       1   
625          626         0       1   
630          631         1       1   
672          673         0       2   
684          685         0       2   
694          695         0       1   
745          746         0       1   
829          830         1       1   
851          852         0       3   

                                                 Name     Sex   Age  SibSp  \
33                              Wheadon, Mr. Edward H    male  66.0      0   
54                     Ostby, Mr. Engelhart Cornelius    male  65.0      0   
96                          Goldschmidt, Mr. George B    male  71.0      0   
116                              Connors, Mr. Patrick    male  70.5      0   
170                         Van der hoef, Mr. Wyckoff    male  61.0      0   
252                         Stead, Mr. William Thomas    male  62.0      0   
275                 Andrews, Miss. Kornelia Theodosia  female  63.0      1   
280                                  Duane, Mr. Frank    male  65.0      0   
326                         Nysveen, Mr. Johan Hansen    male  61.0      0   
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  female  60.0      1   
438                                 Fortune, Mr. Mark    male  64.0      1   
456                         Millet, Mr. Francis Davis    male  65.0      0   
483                            Turkula, Mrs. (Hedwig)  female  63.0      0   
493                           Artagaveytia, Mr. Ramon    male  71.0      0   
545                      Nicholson, Mr. Arthur Ernest    male  64.0      0   
555                                Wright, Mr. George    male  62.0      0   
570                                Harris, Mr. George    male  62.0      0   
587                  Frolicher-Stehli, Mr. Maxmillian    male  60.0      1   
625                             Sutton, Mr. Frederick    male  61.0      0   
630              Barkworth, Mr. Algernon Henry Wilson    male  80.0      0   
672                       Mitchell, Mr. Henry Michael    male  70.0      0   
684                 Brown, Mr. Thomas William Solomon    male  60.0      1   
694                                   Weir, Col. John    male  60.0      0   
745                      Crosby, Capt. Edward Gifford    male  70.0      1   
829         Stone, Mrs. George Nelson (Martha Evelyn)  female  62.0      0   
851                               Svensson, Mr. Johan    male  74.0      0   

     Parch       Ticket      Fare        Cabin Embarked  
33       0   C.A. 24579   10.5000          NaN        S  
54       1       113509   61.9792          B30        C  
96       0     PC 17754   34.6542           A5        C  
116      0       370369    7.7500          NaN        Q  
170      0       111240   33.5000          B19        S  
252      0       113514   26.5500          C87        S  
275      0        13502   77.9583           D7        S  
280      0       336439    7.7500          NaN        Q  
326      0       345364    6.2375          NaN        S  
366      0       110813   75.2500          D37        C  
438      4        19950  263.0000  C23 C25 C27        S  
456      0        13509   26.5500          E38        S  
483      0         4134    9.5875          NaN        S  
493      0     PC 17609   49.5042          NaN        C  
5

In [79]:
#iloc(integerloc), loc 활용
titanic_df.iloc[0,8]

'A/5 21171'

In [80]:
# loc는 문자, A/5 뭐시기 찾기  칼럼명을 통해 접근 
titanic_df.loc[0,"Ticket"]

'A/5 21171'

In [99]:
# 60세가 넘는 승객의 이름과 나이를 조회하라 
titanic_df[titanic_df["Age"]>=60].loc[:,["Name", "Age"]]
# or 

Name   Age
33                              Wheadon, Mr. Edward H  66.0
54                     Ostby, Mr. Engelhart Cornelius  65.0
96                          Goldschmidt, Mr. George B  71.0
116                              Connors, Mr. Patrick  70.5
170                         Van der hoef, Mr. Wyckoff  61.0
252                         Stead, Mr. William Thomas  62.0
275                 Andrews, Miss. Kornelia Theodosia  63.0
280                                  Duane, Mr. Frank  65.0
326                         Nysveen, Mr. Johan Hansen  61.0
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  60.0
438                                 Fortune, Mr. Mark  64.0
456                         Millet, Mr. Francis Davis  65.0
483                            Turkula, Mrs. (Hedwig)  63.0
493                           Artagaveytia, Mr. Ramon  71.0
545                      Nicholson, Mr. Arthur Ernest  64.0
555                                Wright, Mr. George  62.0
570                                Harris, Mr. George  62.0
587                  Frolicher-Stehli, Mr. Maxmillian  60.0
625                             Sutton, Mr. Frederick  61.0
630              Barkworth, Mr. Algernon Henry Wilson  80.0
672                       Mitchell, Mr. Henry Michael  70.0
684                 Brown, Mr. Thomas William Solomon  60.0
694                                   Weir, Col. John  60.0
745                      Crosby, Capt. Edward Gifford  70.0
829         Stone, Mrs. George Nelson (Martha Evelyn)  62.0
851                               Svensson, Mr. Johan  74.0

In [108]:
# 60세가 넘고 1등칸에 승선한 여성을 구하여라 
# 조건이 많아졌는데, 
cond1 = titanic_df["Age"]>60
cond2 = titanic_df["Pclass"] == 1
cond3 = titanic_df["Sex"] == 'female'
#titanic_df[cond1 &cond2 & cond3]
titanic_df[(titanic_df["Age"]>=60 )& (titanic_df["Pclass"]==1)].loc[:,["Name", "Age"]]

Name   Age
54                     Ostby, Mr. Engelhart Cornelius  65.0
96                          Goldschmidt, Mr. George B  71.0
170                         Van der hoef, Mr. Wyckoff  61.0
252                         Stead, Mr. William Thomas  62.0
275                 Andrews, Miss. Kornelia Theodosia  63.0
366  Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  60.0
438                                 Fortune, Mr. Mark  64.0
456                         Millet, Mr. Francis Davis  65.0
493                           Artagaveytia, Mr. Ramon  71.0
545                      Nicholson, Mr. Arthur Ernest  64.0
555                                Wright, Mr. George  62.0
587                  Frolicher-Stehli, Mr. Maxmillian  60.0
625                             Sutton, Mr. Frederick  61.0
630              Barkworth, Mr. Algernon Henry Wilson  80.0
694                                   Weir, Col. John  60.0
745                      Crosby, Capt. Edward Gifford  70.0
829         Stone, Mrs. George Nelson (Martha Evelyn)  62.0

In [109]:
#Aggregation sort_values()
titanic_df.sort_values(by=["Name"])

PassengerId  Survived  Pclass                                   Name  \
845          846         0       3                    Abbing, Mr. Anthony   
746          747         0       3            Abbott, Mr. Rossmore Edward   
279          280         1       3       Abbott, Mrs. Stanton (Rosa Hunt)   
308          309         0       2                    Abelson, Mr. Samuel   
874          875         1       2  Abelson, Mrs. Samuel (Hannah Wizosky)   
..           ...       ...     ...                                    ...   
286          287         1       3                de Mulder, Mr. Theodore   
282          283         0       3              de Pelsmaeker, Mr. Alfons   
361          362         0       2              del Carlo, Mr. Sebastiano   
153          154         0       3        van Billiard, Mr. Austin Blyler   
868          869         0       3            van Melkebeke, Mr. Philemon   

        Sex   Age  SibSp  Parch         Ticket     Fare Cabin Embarked  
845    male  42.0      0      0      C.A. 5547   7.5500   NaN        S  
746    male  16.0      1      1      C.A. 2673  20.2500   NaN        S  
279  female  35.0      1      1      C.A. 2673  20.2500   NaN        S  
308    male  30.0      1      0      P/PP 3381  24.0000   NaN        C  
874  female  28.0      1      0      P/PP 3381  24.0000   NaN        C  
..      ...   ...    ...    ...            ...      ...   ...      ...  
286    male  30.0      0      0         345774   9.5000   NaN        S  
282    male  16.0      0      0         345778   9.5000   NaN        S  
361    male  29.0      1      0  SC/PARIS 2167  27.7208   NaN        C  
153    male  40.5      0      2       A/5. 851  14.5000   NaN        S  
868    male   NaN      0      0         345777   9.5000   NaN        S  

[891 rows x 12 columns]

In [110]:
#titanic df Pclass Name 열을 기준으로 정렬하라
titanic_df.sort_values(by=['Pclass','Name'])

PassengerId  Survived  Pclass  \
730          731         1       1   
305          306         1       1   
297          298         0       1   
498          499         0       1   
460          461         1       1   
..           ...       ...     ...   
559          560         1       3   
286          287         1       3   
282          283         0       3   
153          154         0       3   
868          869         0       3   

                                                Name     Sex    Age  SibSp  \
730                    Allen, Miss. Elisabeth Walton  female  29.00      0   
305                   Allison, Master. Hudson Trevor    male   0.92      1   
297                     Allison, Miss. Helen Loraine  female   2.00      1   
498  Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00      1   
460                              Anderson, Mr. Harry    male  48.00      0   
..                                               ...     ...    ...    ...   
559     de Messemaeker, Mrs. Guillaume Joseph (Emma)  female  36.00      1   
286                          de Mulder, Mr. Theodore    male  30.00      0   
282                        de Pelsmaeker, Mr. Alfons    male  16.00      0   
153                  van Billiard, Mr. Austin Blyler    male  40.50      0   
868                      van Melkebeke, Mr. Philemon    male    NaN      0   

     Parch    Ticket      Fare    Cabin Embarked  
730      0     24160  211.3375       B5        S  
305      2    113781  151.5500  C22 C26        S  
297      2    113781  151.5500  C22 C26        S  
498      2    113781  151.5500  C22 C26        S  
460      0     19952   26.5500      E12        S  
..     ...       ...       ...      ...      ...  
559      0    345572   17.4000      NaN        S  
286      0    345774    9.5000      NaN        S  
282      0    345778    9.5000      NaN        S  
153      2  A/5. 851   14.5000      NaN        S  
868      0    345777    9.5000      NaN        S  

[891 rows x 12 columns]

In [117]:
# Aggregation 함수 적용, 집계함수 
# 10) titanic_df의 선실 등급별 승객수를 groupby를 활용하여 조회하라
titanic_df.groupby("Pclass").count() # 그 그룹에 속한 사람들을 조회하는 것 


PassengerId  Survived  Name  Sex  Age  SibSp  Parch  Ticket  Fare  \
Pclass                                                                      
1               216       216   216  216  186    216    216     216   216   
2               184       184   184  184  173    184    184     184   184   
3               491       491   491  491  355    491    491     491   491   

        Cabin  Embarked  
Pclass                   
1         176       214  
2          16       184  
3          12       491

In [121]:
# 11) titanic_df의 선실 등급별 승객수를 pivot_table를 활용하여 조회하라
titanic_df.pivot_table(index="Pclass", aggfunc='count')

Age  Cabin  Embarked  Fare  Name  Parch  PassengerId  Sex  SibSp  \
Pclass                                                                     
1       186    176       214   216   216    216          216  216    216   
2       173     16       184   184   184    184          184  184    184   
3       355     12       491   491   491    491          491  491    491   

        Survived  Ticket  
Pclass                    
1            216     216  
2            184     184  
3            491     491

In [128]:
# 12) titanic_df의 선실 등급별로 총 승객수, 생존자수를 조회하라(groupby, pivot_table)
# groupby
titanic_df.groupby("Pclass")[['PassengerId','Survived']].agg({"PassengerId": 'count', 'Survived': 'sum'})


PassengerId  Survived
Pclass                       
1               216       136
2               184        87
3               491       119

In [127]:
#pivot_table
titanic_df.pivot_table(index ="Pclass", 
                       values=['PassengerId', 'Survived'],
                       aggfunc={"PassengerId": 'count', 'Survived': 'sum'})


PassengerId  Survived
Pclass                       
1               216       136
2               184        87
3               491       119

In [130]:
#타이타닉 데이터에서 결측지 확인하기 - isna() fillna()
# 방법 1) df의 .info() 활용하기 
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [132]:
# 방법 2) df의 isna() 메소드 활용하기 
titanic_df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [139]:
# 결측치가 있는 데이터를 버린다? 그러면 좋은 방법일 수는 없겟지
# 그러면 
# 어떤 데이터를 선택하여 어떻게 분석할 것인가?
# 1) cabin데이터 버리지 말고 fillna를 통해 cabin열의 결측치를 모두 'C000'으로 채우자
titanic_df['Cabin'] = titanic_df["Cabin"].fillna("C000")
titanic_df
# 앞 뒤의 데이터의 반을 넣거나 평균으로 채우거나 
# 앞에 것으로 채우거나 뒤에 걸로 채움 backward forward
# 이런 기법이 있음
# ex) 주식시장 비교 

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500  C000        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250  C000        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500  C000        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000  C000        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500  C000        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500  C000        Q  

[891 rows x 12 columns]

In [140]:
#apply, lambda 복수의 데이터를 하나의 방식으로 변환할 때 많이 씀 (익명함수)

In [141]:
def get_triple(x):
    return x*3

In [143]:
# get_triple을 람다 함수로 작성하시오
(lambda x: x*3)(2)

6

In [144]:
a = lambda x: x*3

In [145]:
a(2)

6

In [148]:
#람다를 활용하여 타이타닉 데이터프레임의 Name 의 글자수를 알려주는 Name_len열을 생성하시오 
titanic_df["Namelen"] = titanic_df["Name"].apply(lambda x: len(x))
titanic_df["Namelen"]

0      23
1      51
2      22
3      44
4      24
       ..
886    21
887    28
888    40
889    21
890    19
Name: Namelen, Length: 891, dtype: int64

In [151]:
#타이타닉 성별의 데이터를 받아 'gender_person'열을 추가하라 
titanic_df["gender_person"] = titanic_df["Sex"].apply(lambda x: x+'_person')

In [152]:
titanic_df["gender_person"]

0        male_person
1      female_person
2      female_person
3      female_person
4        male_person
           ...      
886      male_person
887    female_person
888    female_person
889      male_person
890      male_person
Name: gender_person, Length: 891, dtype: object

In [153]:
# 타이타닉 age열의 정보 중에 18세 이상 22세 이하이면 young을 갖고 아니면 not young 
titanic_df["Age_Cat"] = titanic_df["Age"].apply(lambda x: 'Young' if 18<=x<=22 else 'Not Young' )

In [154]:
titanic_df["Age_Cat"]

0          Young
1      Not Young
2      Not Young
3      Not Young
4      Not Young
         ...    
886    Not Young
887        Young
888    Not Young
889    Not Young
890    Not Young
Name: Age_Cat, Length: 891, dtype: object

In [156]:
#10대 20대 30대 40대 구분을 해봅시다 
def get_age_cat(x):
    if x<=5:
        cat = 'Baby'
    elif x<=12:
        cat = 'Child'
    elif x<=18:
        cat = 'Teenager'
    elif x<=25:
        cat = 'Student'
    elif x<=35:
        cat = 'Young Adult'
    elif x<=60:
        cat = 'Adult'
    else:
        cat = 'Elderly'
    return cat

In [157]:
titanic_df["Age_Cat_2"] = titanic_df["Age"].apply(get_age_cat)


In [158]:
titanic_df["Age_Cat_2"] 

0          Student
1            Adult
2      Young Adult
3      Young Adult
4      Young Adult
          ...     
886    Young Adult
887        Student
888        Elderly
889    Young Adult
890    Young Adult
Name: Age_Cat_2, Length: 891, dtype: object

In [159]:
# 1000단위 , 써있는 숫자 가공하기 위해 lambda 씀 


In [160]:
# 라벨 인코딩 

# 모든 문자열 숫자는 반드시  숫자형으로 변경해야 함 
# 식별자는 없애야 함 -> 큰 이슈 중 하나임 
# label을 숫자 코드로 바꾸는 것을 라벨 인코딩이라고 함 


In [161]:
from sklearn.preprocessing import LabelEncoder

items =  ['TV', '냉장고','전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서','믹서']
encoder = LabelEncoder() #인스턴스 생성 
encoder.fit(items)
labels= encoder.transform(items)
print(labels)
#근데 라벨 인코딩 순서가 다름? 컴퓨터가 문자열을 숫자로 바꾸고 ascii 코드, 유니코드 순서로 만들어지기 때문에!

[0 1 4 5 3 3 2 2]


In [162]:
#라벨 인코딩 규칙 
encoder.classes_

array(['TV', '냉장고', '믹서', '선풍기', '전자렌지', '컴퓨터'], dtype='<U4')

In [165]:
encoder.inverse_transform(labels)

array(['TV', '냉장고', '전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서', '믹서'], dtype='<U4')

In [166]:
# 원핫 인코딩
# 라벨 인코딩은 대소 구분 없이 구분하기 위한 라벨(이름표)로 작동함
# 그런데 이렇게 하니까 대소를 구분하는 컴퓨터가 원치 않게 작동함
# 그래서 나온 것이 원핫 인코딩
# 하나만 참이 있는 것으로 인코딩 하는 것!

In [167]:
#원핫 인코딩 많이 씀 

In [168]:
#먼저 라벨 인코딩으로 변환 후 원핫 인코딩 해야함

In [179]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items =  ['TV', '냉장고','전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서','믹서']
encoder  = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)

# 원핫 인코딩 하기 전 2차원 배열로 구조 변경
labels = labels.reshape((-1,1)) #resahpe: 구조의 모양을 tuple로 넣음 // 몇 행일지는 모르겠지만 한 행에는 무조건 데이터 하나만 들어가야 함 

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)
oh_labels.toarray()

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

In [181]:
# pandas를 활용한 원핫 인코딩 만들기 - get_dummies()
import pandas as pd
df = pd.DataFrame({"items":['TV', '냉장고','전자렌지', '컴퓨터', '선풍기', '선풍기', '믹서','믹서']})

In [182]:
result = pd.get_dummies(df)
result
result.values

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0]], dtype=uint8)

In [173]:
a1 = np.array(range(0,12))
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [172]:
a1.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [174]:
a2 = np.array(range(0,12))

In [175]:
a2.reshape((3, -1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#데이터 스캐일링 - 서로 다른 변수의 값 범위를 일정한 수준으로 맞추는 작업, 실제 특성값의 크기와 상관없이 동일한 조건으로 비교
# 표준화, 정규화 

In [184]:
# 표준화(Standardization)
# 평균 0, 분산 1인 가우시안 정규 분포를 가진 값으로 변환, 각 특성값이 0에서 표준편차의 몇 배만큼 떨 어져 있는가를 표시


# 정규화(Normalization)
# 서로 다른 피처의 크기를 통일하기 위해 크기를 변환, 동일한 크기 단위로 비교(최소 0 ~ 최대 1의 범위 로 변환)

# 110 자료 24p 다시 공부하기 

In [186]:
# StandardSCaler 
from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()
iris.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [187]:
df = pd.DataFrame(data=iris.data)
df.describe()

0           1           2           3
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333
std      0.828066    0.435866    1.765298    0.762238
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [189]:
# 표준화 Standardization 

iris_df = pd.DataFrame(data= iris.data, columns=iris.feature_names)
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [192]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(iris_df)
iris_scaled = scaler.transform(iris_df)
np.set_printoptions(precision=6, suppress=True)
iris_scaled

array([[-0.900681,  1.019004, -1.340227, -1.315444],
       [-1.143017, -0.131979, -1.340227, -1.315444],
       [-1.385353,  0.328414, -1.397064, -1.315444],
       [-1.506521,  0.098217, -1.283389, -1.315444],
       [-1.021849,  1.249201, -1.340227, -1.315444],
       [-0.537178,  1.939791, -1.169714, -1.05218 ],
       [-1.506521,  0.788808, -1.340227, -1.183812],
       [-1.021849,  0.788808, -1.283389, -1.315444],
       [-1.748856, -0.362176, -1.340227, -1.315444],
       [-1.143017,  0.098217, -1.283389, -1.447076],
       [-0.537178,  1.479398, -1.283389, -1.315444],
       [-1.264185,  0.788808, -1.226552, -1.315444],
       [-1.264185, -0.131979, -1.340227, -1.447076],
       [-1.870024, -0.131979, -1.510739, -1.447076],
       [-0.052506,  2.169988, -1.453901, -1.315444],
       [-0.173674,  3.090775, -1.283389, -1.05218 ],
       [-0.537178,  1.939791, -1.397064, -1.05218 ],
       [-0.900681,  1.019004, -1.340227, -1.183812],
       [-0.173674,  1.709595, -1.169714, -1.18

In [194]:
iris_scaled_df = pd.DataFrame(iris_scaled)
iris_scaled_df.describe()

0             1             2             3
count  1.500000e+02  1.500000e+02  1.500000e+02  1.500000e+02
mean  -1.468455e-15 -1.823726e-15 -1.610564e-15 -9.473903e-16
std    1.003350e+00  1.003350e+00  1.003350e+00  1.003350e+00
min   -1.870024e+00 -2.433947e+00 -1.567576e+00 -1.447076e+00
25%   -9.006812e-01 -5.923730e-01 -1.226552e+00 -1.183812e+00
50%   -5.250608e-02 -1.319795e-01  3.364776e-01  1.325097e-01
75%    6.745011e-01  5.586108e-01  7.627583e-01  7.906707e-01
max    2.492019e+00  3.090775e+00  1.785832e+00  1.712096e+00

In [196]:
# 평균과 분산이 각각 0, 1에 수렴하는 것을 볼 수 있다
pd.options.display.float_format = '{:.5f}'.format
iris_scaled_df.describe()

0         1         2         3
count 150.00000 150.00000 150.00000 150.00000
mean   -0.00000  -0.00000  -0.00000  -0.00000
std     1.00335   1.00335   1.00335   1.00335
min    -1.87002  -2.43395  -1.56758  -1.44708
25%    -0.90068  -0.59237  -1.22655  -1.18381
50%    -0.05251  -0.13198   0.33648   0.13251
75%     0.67450   0.55861   0.76276   0.79067
max     2.49202   3.09078   1.78583   1.71210

In [197]:
#minmaxscaler

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scaler.fit(iris.data)
scaler.transform(iris.data) #데이터를 전부 0과 1사이의 값으로 

array([[0.222222, 0.625   , 0.067797, 0.041667],
       [0.166667, 0.416667, 0.067797, 0.041667],
       [0.111111, 0.5     , 0.050847, 0.041667],
       [0.083333, 0.458333, 0.084746, 0.041667],
       [0.194444, 0.666667, 0.067797, 0.041667],
       [0.305556, 0.791667, 0.118644, 0.125   ],
       [0.083333, 0.583333, 0.067797, 0.083333],
       [0.194444, 0.583333, 0.084746, 0.041667],
       [0.027778, 0.375   , 0.067797, 0.041667],
       [0.166667, 0.458333, 0.084746, 0.      ],
       [0.305556, 0.708333, 0.084746, 0.041667],
       [0.138889, 0.583333, 0.101695, 0.041667],
       [0.138889, 0.416667, 0.067797, 0.      ],
       [0.      , 0.416667, 0.016949, 0.      ],
       [0.416667, 0.833333, 0.033898, 0.041667],
       [0.388889, 1.      , 0.084746, 0.125   ],
       [0.305556, 0.791667, 0.050847, 0.125   ],
       [0.222222, 0.625   , 0.067797, 0.083333],
       [0.388889, 0.75    , 0.118644, 0.083333],
       [0.222222, 0.75    , 0.084746, 0.083333],
       [0.305556, 0.

In [198]:
# fit 은 train data에서 정한거라  다시 fit 하면 안됨 trained data로 해야됨
# 다시 기준을 정하면 안되고 transform만 해야한다는 것임 
# 새로운 기준 만들지 마라!


In [ ]:
# testdata는 fit 하지말고 transform만 해야된다는 것임!
