# 230116 파이썬 수업 내용

부스트캠프 코테 1번 문제 

In [10]:
def Solution(st):
    #ls = map(int, list(st))
    st = list(map(int, st))
    ip = []

    while len(st) != 0:
        buffer = []
        byteToInt = 0
        for i in range(7,-1,-1):
            byteToInt += (st[0]*2)**i
            del st[0]
        ip.append(byteToInt)

    return ".".join(list(map(str, ip)))


st = "10101101101110000100101100101101"
Solution(st)

'173.185.75.45'

In [11]:
class Student:
    def __init__(self):
        self.hello = "안녕하세요"

stu_a= Student()

stu_a.hello = "안녕하세요"
print(stu_a.hello)

안녕하세요


In [14]:
class Person : 
    def __init__(self, name, age) -> None:
        self.name = name
        self.age = age

p1 = Person("name1", 40)
p2 = Person("name2", 32)

p1.name = "name1"
p1.age = 40

p2.name = "name"
p2.age = 32

In [15]:
p1.__dict__

{'name': 'name1', 'age': 40}

In [22]:
class Person2:
    def __init__(self, name, age, address) -> None:
        self.hello = "안녕하세요"
        self.name = name
        self.age = age 
        self.address = address

    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")

humanlist = []

for _ in range(2):
    name = input("이름은 무엇인가요?:")
    age = int(input("나이는 무엇인가요?: "))
    address = input("주소는 무엇인가요?")
    info = Person2(name,age,address)
    humanlist.append(info)

print("첫번쨰 이름: ",humanlist[0].name)    
print("첫번쨰 나이: ", humanlist[0].age)
print("첫번쨰 주소: ", humanlist[0].address)

print("두번쨰 이름: ", humanlist[1].name)
print("두번쨰 나이: ", humanlist[1].age)
print("두번쨰 주소: ", humanlist[1].address)

첫번쨰 이름:  3
첫번쨰 나이:  4
첫번쨰 주소:  5
두번쨰 이름:  6
두번쨰 나이:  7
두번쨰 주소:  8


In [23]:
class ClassName:
    def __init__(self, param1, param2) -> None:
        self.attr = param1
        self.__attr2 = param2

    

In [ ]:
class Person3:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet

    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")




In [37]:
class Annie:
    def __init__(self,hp,mp,ap):
        self.__hp = hp
        self.__mp = mp
        self.__ap = ap

    def tibbers(self):
        return self.__ap*0.65+400


a,b,c = map(float, input("체력과 마나, AP를 입력하세요").split(" "))
ch = Annie(a,b,c)
print(ch.tibbers())


401.95


## NUMPY

In [3]:
import numpy as np

#ndarray == N-dimensional Array

ar = np.array([_ for _ in range(10)])
ar.shape

(10,)

In [44]:
!conda list

# packages in environment at /Users/minholee/opt/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39hca03da5_1  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39hca03da5_0  
anaconda-navigator        2.3.1            py39hca03da5_0  
anaconda-project          0.11.1           py39hca03da5_0  
anyio                     3.5.0            py39hca03da5_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
appnope                   0.1.2           py39hca03da5_1001  
appscript                 1.1.2            py39h1a28f6b_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h1a28f6b_0  
astroid                   2.11.7           py39hca03da5_0  
astropy                   5.1              py39heec5a64_0  
asttokens                 2.0

In [47]:
ar5 = np.array(["가나다라마" for _ in range(5)], 'U5')
print(ar5)


['가나다라마' '가나다라마' '가나다라마' '가나다라마' '가나다라마']


In [46]:
x = np.array([1,2,3])
x.dtype

np.inf()



dtype('int64')

벡터화 연산을 지원한다<br>
하나의 명령어로 처리하는 벡터화 연산을 지원합니다.

In [57]:
data = [int(_) for _ in range(0,10)]

x = np.array(data)
print(x)
2*x
print(x)



[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [58]:
a = np.array([1,2,3])
b = np.array([10,20,30])

2*a+b

array([12, 24, 36])

In [64]:
a<<1

array([2, 4, 6])

In [60]:
b>10

array([False,  True,  True])

In [62]:
(a==2)&(b>10)

array([False,  True, False])

In [70]:
c = np.array([[1,2,3],
            [4,5,6]])

c.shape
len(c[0])

3

In [73]:
answer = np.array([[10,20,30,40],[int(_) for _ in range(50, 81, 10)]])
print(answer)


[[10 20 30 40]
 [50 60 70 80]]


1차원으로 만들고 dimesion 으로 만들 수도 있음


3차원 배열

In [74]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [75]:
a[0,:]

array([0, 1, 2, 3])

In [77]:
#reshape 을 통해 생겨먹은거 바꿀 수도 있다
np.array([_ for _ in range(8)]).reshape(4,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

reshape 을 통한 1차원 배열을 2차원 배열로

In [132]:
m =  np.array([_ for _ in range(15)]).reshape(3,5)

#1
print(m[1,2])
#2
print(m[-1,-1])
# 3
print(m[1,1:3])
#4
print(m[1:3,2])
# 5
print(m[0:2,3:5])

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


In [134]:
#Answer

m[1,2]
m[2,4]
m[2,-1]
m[1,1:3]
m[1:3, 2]
m[:2, 3:5]

array([[3, 4],
       [8, 9]])

### 이런 메소드가 있다 
- zeros, ones
- zeros_like, ones_like
- empty
- arange
- linespace, logspace
- zeros

In [135]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [137]:
#5행 2열짜리 int type 배열 생성
c = np.zeros((5,2), dtype="i")
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [139]:
b1 = np.ones((2,3))
b2 = np.zeros((3,3))
print(b1)
print(b2)

np.vstack([b1,b2])

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [141]:
#indexer 

np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [143]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [144]:
a = np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [146]:
np.tile(a,(3,2))

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [4]:
b1 = np.zeros((3,3))
b2 = np.ones((3,2))
bHstack = np.hstack([b1, b2])
ar = np.array([_ for _ in range(10, 151,10)]).reshape(3,5)
abVstack = np.vstack([bHstack, ar])
np.vstack([abVstack,abVstack])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])