# 2023 01 17 Numpy 계속

In [64]:


class Calculator:
    value = 0 #초기값은 0으로 갖습니다
    
    def add(self,*args):
        """value값에 인수로 받은 값을 가산합니다"""
        if len(args) == 0:
            print("숫자를 입력해주세요")
            return
        if type(args)==tuple:
            self.value += np.sum(args)
            return    
            
        for _ in args:
            self.value+=_
            
    def minus(self, *args):
        """value값에 인수로 받은 값을 감산합니다"""
        if len(args) == 0:
            print("숫자를 입력해주세요")
            return
        if type(args) == tuple:
            self.value -= np.sum(args)
            return
        
        for _ in args:
            self.value -= _

    def show_value(self):
        """value 를 보여줍니다"""
        print(f"현재 값은 {self.value}입니다.")
        
c = Calculator()
c.add([10,2])
c.add(range(1,5))
c.minus(20)
c.show_value()

현재 값은 2입니다.


In [67]:
from math import sinh
reversed(list(range(1,11)))

z= "a;b;c;"
k = z.split(";")
len(k)

4

In [71]:
a = np.array([1,2,3])
b = np.array([10,29,30])

np.vstack([a,b])



array([[ 1,  2,  3],
       [10, 29, 30]])

In [ ]:
x = np.arange(1,10001)
y = np.arange(10001, 20001)



In [72]:
a = np.array([1.0,2.0,3.0])
b = 2.0
a*b # 스칼라가 늘어나서 연산된다


array([2., 4., 6.])

In [74]:
y = np.ones_like(a)
y

array([1., 1., 1.])

In [78]:
x = np.arange(20).reshape(2,5,-1)
x
x.max(axis=0)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

mean(): 평균값

median(): 중앙값

np.all(): 배열 요소가 True 일떄 true를 반환

np.any(): 하나라도 true면 true를 반환

In [91]:
import numpy as np

practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

np.max(practice)  #전체의 최댓값
np.sum(practice, axis=1)  # 각 행의 합
np.max(practice, axis=1)  # 각 행의 최댓값
np.mean(practice, axis=0)  # 각 열의 평균
np.min(practice, axis=0)  # 각 열의 최솟값


9.0

In [92]:
np.max(practice)  #전체의 최댓값

9.0

In [88]:
np.sum(practice, axis =1)  # 각 행의 합

array([32. , 30.7, 34.3, 24.7, 29.7])

In [94]:
np.max(practice, axis=1)  # 각 행의 최댓값

array([8. , 9. , 8.9, 8.2, 8.9])

In [99]:
np.mean(practice, axis=0) # 각 열의 평균

array([4.02, 5.4 , 4.72, 5.2 , 5.64, 5.3 ])

In [100]:
np.min(practice, axis=0)# 각 열의 최솟값

array([0.7, 1.1, 2.7, 2.1, 2.8, 0.2])

In [110]:
scores = np.array([[1,2,3,4],[46,99,100,71],[81,59,90,100]])


english_ranking = np.argsort(scores[1,:])
print(scores[:,english_ranking])


[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [111]:
np.random.rand(10)

array([0.38199871, 0.1418194 , 0.71562764, 0.62453567, 0.88723912,
       0.18394638, 0.75971967, 0.09279039, 0.77717626, 0.55670009])

In [112]:
np.random.seed(0)
np.random.rand(5)
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [113]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [114]:
np.random.shuffle(x)
x

array([5, 1, 8, 2, 6, 7, 0, 3, 4, 9])

In [120]:
np.random.choice(x,size=None, replace=True,p=None)

5

In [122]:
k = np.arange(5)
np.random.choice(k,5,replace=False) # shuffle 명령과 같다


array([1, 4, 2, 3, 0])

In [124]:
np.random.choice(5,3,replace=False)# 3개만 선택

array([1, 3, 0])

In [126]:
np.random.choice(5,10) #반복해서 10개

array([1, 1, 1, 3, 3, 2, 3, 0, 3, 4])

In [131]:
np.random.choice(5,10, p=[0.1,0,0.3,0.6,0])

array([3, 3, 3, 2, 2, 2, 3, 2, 3, 2])

rand: 0-1사이 균일 분포
randn: 표준 정규 분포
randint: 균일 분포의 정수 난수
-> 이거는 표준 라이브러리랑 다른데, 
```
numpy.random.randint(low, high=None, low=None)
```
high를 입력하지 않으면 0과 low 사이의 숫자를, high 를 입력하면 low와 high 의 숫자를 출력함  

In [150]:
np.random.seed(0)
coin_result = np.random.randint(0,2,100)

coin_result
coin_result.sum()/len(coin_result)

0.56

In [153]:
np.random.seed(0)
dice = np.random.randint(1,7,100)
np.mean(dice)

3.42

In [154]:
np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [158]:
a = np.array(['a','b','b','c','a'])
index, count = np.unique(a, return_counts=True)
index

array(['a', 'b', 'c'], dtype='<U1')

In [159]:
count

array([2, 2, 1])

In [162]:
np.bincount([1,1,2,2,2,3], minlength=6)

array([0, 2, 3, 1, 0, 0])